FROM mongo:7.0
RUN apt-get update && apt-get install -y mongodb-database-tools
COPY filmes.json atores.json generos.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/import.sh
