services:
  mongodb:
    image: mongo:7.0
    container_name: projeto_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  api_dados:
    build: ./api_dados
    container_name: projeto_api_dados
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/projetoEW
      - JWT_SECRET=${JWT_SECRET:-EngWeb2026-Projeto-Secret}
      - PORT=16000
    depends_on:
      - mongodb
    volumes:
      - ./api_dados:/usr/src/app
      - /usr/src/app/node_modules

  interface:
    build: ./interface
    container_name: projeto_interface
    ports:
      - "16001:16001"
    environment:
      - API_URL=http://api_dados:16000
      - PORT=16001
    depends_on:
      - api_dados
    volumes:
      - ./interface:/usr/src/app
      - /usr/src/app/node_modules
